#!/usr/local/bin/spar

procedure init_countries is

pragma annotate( summary, "init_countries" )
              @( description, "Initialize the list of countries " )
              @( author, "Ken O. Burtch" );
pragma license( gplv3 );
pragma software_model( shell_script );

with separate "config/contributors.inc.sp";
with separate "lib/world.inc.sp";
with separate "lib/common.inc.sp";

countries_file : btree_io.file( country_data );

r : country_data;

begin

btree_io.create( countries_file, countries_path, countries_width, countries_width );
r.iso3166 := "AD";
r.common_name    := "Andorra";
r.suffix  := ".ad";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AE";
r.common_name := "United Arab Emirates";
r.suffix := ".ae";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AF";
r.common_name := "Afghanistan";
r.suffix := ".af";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AG";
r.common_name := "Antigua and Barbuda";
r.suffix := ".ag";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AI";
r.common_name := "Anguilla";
r.suffix := ".ai";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AL";
r.common_name := "Albania";
r.suffix := ".al";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AM";
r.common_name := "Armenia";
r.suffix := ".am";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AO";
r.common_name := "Angola";
r.suffix := ".ao";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AQ";
r.common_name := "Antarctica";
r.suffix := ".aq";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AR";
r.common_name := "Argentina";
r.suffix := ".ar";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AS";
r.common_name := "American Samoa";
r.suffix := ".as";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AT";
r.common_name := "Austria";
r.suffix := ".at";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AU";
r.common_name := "Australia";
r.suffix := ".au";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AW";
r.common_name := "Aruba";
r.suffix := ".aw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AX";
r.common_name := "Åland Islands";
r.suffix := ".ax";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "AZ";
r.common_name := "Azerbaijan";
r.suffix := ".az";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BA";
r.common_name := "Bosnia and Herzegovina";
r.suffix := ".ba";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BB";
r.common_name := "Barbados";
r.suffix := ".bb";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BD";
r.common_name := "Bangladesh";
r.suffix := ".bd";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BE";
r.common_name := "Belgium";
r.suffix := ".be";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BF";
r.common_name := "Burkina Faso";
r.suffix := ".bf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BG";
r.common_name := "Bulgaria";
r.suffix := ".bg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BH";
r.common_name := "Bahrain";
r.suffix := ".bh";
r.iso3166 := "BI";
btree_io.set( countries_file, r.iso3166, r );
r.common_name := "Burundi";
r.suffix := ".bi";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BJ";
r.common_name := "Benin";
r.suffix := ".bj";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BL";
r.common_name := "Saint Barthélemy";
r.suffix := ".bl";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BM";
r.common_name := "Bermuda";
r.suffix := ".bm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BN";
r.common_name := "Brunei Darussalam";
r.suffix := ".bn";
r.iso3166 := "BO";
btree_io.set( countries_file, r.iso3166, r );
r.common_name := "Bolivia, Plurinational State of";
r.suffix := ".bo";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BQ";
r.common_name := "Bonaire, Sint Eustatius and Saba";
r.suffix := ".bq";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BR";
r.common_name := "Brazil";
r.suffix := ".br";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BS";
r.common_name := "Bahamas";
r.suffix := ".bs";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BT";
r.common_name := "Bhutan";
r.suffix := ".bt";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BV";
r.common_name := "Bouvet Island";
r.suffix := ".bv";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BW";
r.common_name := "Botswana";
r.suffix := ".bw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BY";
r.common_name := "Belarus";
r.suffix := ".by";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "BZ";
r.common_name := "Belize";
r.suffix := ".bz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CA";
r.common_name := "Canada";
r.suffix := ".ca";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CC";
r.common_name := "Cocos (Keeling) Islands";
r.suffix := ".cc";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CD";
r.common_name := "Congo, the Democratic Republic of the";
r.suffix := ".cd";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CF";
r.common_name := "Central African Republic";
r.suffix := "cf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CG";
r.common_name := "Congo";
r.suffix := ".cg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CH";
r.common_name := "Switzerland";
r.suffix := ".ch";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CI";
r.common_name := "Côte d'Ivoire";
r.suffix := ".ci";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CK";
r.common_name := "Cook Islands";
r.suffix := ".ck";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CL";
r.common_name := "Chile";
r.suffix := ".cl";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CM";
r.common_name := "Cameroon";
r.suffix := ".cm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CN";
r.common_name := "China";
r.suffix := ".cn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CO";
r.common_name := "Colombia";
r.suffix := ".co";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CR";
r.common_name := "Costa Rica";
r.suffix := ".cr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CU";
r.common_name := "Cuba";
r.suffix := ".cu";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CV";
r.common_name := "Cabo Verde";
r.suffix := ".cv";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CW";
r.common_name := "Curaçao";
r.suffix := ".cw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CX";
r.common_name := "Christmas Island";
r.suffix := ".cx";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CY";
r.common_name := "Cyprus";
r.suffix := ".cy";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "CZ";
r.common_name := "Czechia";
r.suffix := ".cz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "DE";
r.common_name := "Germany";
r.suffix := ".de";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "DJ";
r.common_name := "Djibouti";
r.suffix := ".dj";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "DK";
r.common_name := "Denmark";
r.suffix := ".dk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "DM";
r.common_name := "Dominica";
r.suffix := ".dm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "DO";
r.common_name := "Dominican Republic";
r.suffix := ".do";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "DZ";
r.common_name := "Algeria";
r.suffix := ".dz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "EC";
r.common_name := "Ecuador";
r.suffix := ".ec";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "EE";
r.common_name := "Estonia";
r.suffix := ".ee";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "EG";
r.common_name := "Egypt";
r.suffix := ".eg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "EH";
r.common_name := "Western Sahara";
r.suffix := ".eh";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ER";
r.common_name := "Eritrea";
r.suffix := ".er";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ES";
r.common_name := "Spain";
r.suffix := ".es";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ET";
r.common_name := "Ethiopia";
r.suffix := ".et";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "FI";
r.common_name := "Finland";
r.suffix := ".fi";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "FJ";
r.common_name := "Fiji";
r.suffix := ".fj";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "FK";
r.common_name := "Falkland Islands (Malvinas)";
r.suffix := ".fk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "FM";
r.common_name := "Micronesia, Federated States of";
r.suffix := ".fm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "FO";
r.common_name := "Faroe Islands";
r.suffix := ".fo";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "FR";
r.common_name := "France";
r.suffix := ".fr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GA";
r.common_name := "Gabon";
r.suffix := ".ga";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GB";
r.common_name := "United Kingdom of Great Britain and Northern Ireland";
r.suffix := ".uk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GD";
r.common_name := "Grenada";
r.suffix := ".gd";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GE";
r.common_name := "Georgia";
r.suffix := ".ge";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GF";
r.common_name := "French Guiana";
r.suffix := ".gf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GG";
r.common_name := "Guernsey";
r.suffix := ".gg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GH";
r.common_name := "Ghana";
r.suffix := ".gh";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GI";
r.common_name := "Gibraltar";
r.suffix := ".gi";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GL";
r.common_name := "Greenland";
r.suffix := ".gl";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GM";
r.common_name := "Gambia";
r.suffix := ".gm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GN";
r.common_name := "Guinea";
r.suffix := ".gn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GP";
r.common_name := "Guadeloupe";
r.suffix := ".gp";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GQ";
r.common_name := "Equatorial Guinea";
r.suffix := ".gq";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GR";
r.common_name := "Greece";
r.suffix := ".gr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GS";
r.common_name := "South Georgia and the South Sandwich Islands";
r.suffix := ".gs";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GT";
r.common_name := "Guatemala";
r.suffix := ".gt";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GU";
r.common_name := "Guam";
r.suffix := ".gu";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GW";
r.common_name := "Guinea-Bissau";
r.suffix := ".gw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "GY";
r.common_name := "Guyana";
r.suffix := ".gy";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "HK";
r.common_name := "Hong Kong";
r.suffix := ".hk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "HM";
r.common_name := "Heard Island and McDonald Islands";
r.suffix := ".hm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "HN";
r.common_name := "Honduras";
r.suffix := ".hn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "HR";
r.common_name := "Croatia";
r.suffix := ".hr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "HT";
r.common_name := "Haiti";
r.suffix := ".ht";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "HU";
r.common_name := "Hungary";
r.suffix := ".hu";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ID";
r.common_name := "Indonesia";
r.suffix := ".id";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IE";
r.common_name := "Ireland";
r.suffix := ".ie";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IL";
r.common_name := "Israel";
r.suffix := ".il";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IM";
r.common_name := "Isle of Man";
r.suffix := ".im";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IN";
r.common_name := "India";
r.suffix := ".in";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IO";
r.common_name := "British Indian Ocean Territory";
r.suffix := ".io";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IQ";
r.common_name := "Iraq";
r.suffix := ".iq";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IR";
r.common_name := "Iran, Islamic Republic of";
r.suffix := ".ir";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IS";
r.common_name := "Iceland";
r.suffix := ".is";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "IT";
r.common_name := "Italy";
r.suffix := ".it";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "JE";
r.common_name := "Jersey";
r.suffix := ".je";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "JM";
r.common_name := "Jamaica";
r.suffix := ".jm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "JO";
r.common_name := "Jordan";
r.suffix := ".jo";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "JP";
r.common_name := "Japan";
r.suffix := ".jp";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KE";
r.common_name := "Kenya";
r.suffix := ".ke";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KG";
r.common_name := "Kyrgyzstan";
r.suffix := ".kg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KH";
r.common_name := "Cambodia";
r.suffix := ".kh";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KI";
r.common_name := "Kiribati";
r.suffix := ".ki";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KM";
r.common_name := "Comoros";
r.suffix := ".km";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KN";
r.common_name := "Saint Kitts and Nevis";
r.suffix := ".kn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KP";
r.common_name := "Korea, Democratic People's Republic of";
r.suffix := ".kp";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KR";
r.common_name := "Korea, Republic of";
r.suffix := ".kr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KW";
r.common_name := "Kuwait";
r.suffix := ".kw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KY";
r.common_name := "Cayman Islands";
r.suffix := ".ky";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "KZ";
r.common_name := "Kazakhstan";
r.suffix := ".kz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LA";
r.common_name := "Lao People's Democratic Republic";
r.suffix := ".la";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LB";
r.common_name := "Lebanon";
r.suffix := ".lb";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LC";
r.common_name := "Saint Lucia";
r.suffix := ".lc";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LI";
r.common_name := "Liechtenstein";
r.suffix := ".li";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LK";
r.common_name := "Sri Lanka";
r.suffix := ".lk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LR";
r.common_name := "Liberia";
r.suffix := ".lr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LS";
r.common_name := "Lesotho";
r.suffix := ".ls";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LT";
r.common_name := "Lithuania";
r.suffix := ".lt";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LU";
r.common_name := "Luxembourg";
r.suffix := ".lu";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LV";
r.common_name := "Latvia";
r.suffix := ".lv";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "LY";
r.common_name := "Libya";
r.suffix := ".ly";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MA";
r.common_name := "Morocco";
r.suffix := ".ma";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MC";
r.common_name := "Monaco";
r.suffix := ".mc";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MD";
r.common_name := "Moldova, Republic of";
r.suffix := ".md";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ME";
r.common_name := "Montenegro";
r.suffix := ".me";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MF";
r.common_name := "Saint Martin (French part)";
r.suffix := ".mf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MG";
r.common_name := "Madagascar";
r.suffix := ".mg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MH";
r.common_name := "Marshall Islands";
r.suffix := ".mh";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MK";
r.common_name := "Macedonia, the former Yugoslav Republic of";
r.suffix := ".mk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ML";
r.common_name := "Mali";
r.suffix := ".ml";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MM";
r.common_name := "Myanmar";
r.suffix := ".mm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MN";
r.common_name := "Mongolia";
r.suffix := ".mn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MO";
r.common_name := "Macao";
r.suffix := ".mo";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MP";
r.common_name := "Northern Mariana Islands";
r.suffix := ".mp";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MQ";
r.common_name := "Martinique";
r.suffix := ".mq";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MR";
r.common_name := "Mauritania";
r.suffix := ".mr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MS";
r.common_name := "Montserrat";
r.suffix := ".ms";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MT";
r.common_name := "Malta";
r.suffix := ".mt";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MU";
r.common_name := "Mauritius";
r.suffix := ".mu";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MV";
r.common_name := "Maldives";
r.suffix := ".mv";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MW";
r.common_name := "Malawi";
r.suffix := ".mw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MX";
r.common_name := "Mexico";
r.suffix := ".mx";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MY";
r.common_name := "Malaysia";
r.suffix := ".my";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "MZ";
r.common_name := "Mozambique";
r.suffix := ".mz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NA";
r.common_name := "Namibia";
r.suffix := ".na";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NC";
r.common_name := "New Caledonia";
r.suffix := ".nc";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NE";
r.common_name := "Niger";
r.suffix := ".ne";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NF";
r.common_name := "Norfolk Island";
r.suffix := ".nf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NG";
r.common_name := "Nigeria";
r.suffix := ".ng";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NI";
r.common_name := "Nicaragua";
r.suffix := ".ni";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NL";
r.common_name := "Netherlands";
r.suffix := ".nl";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NO";
r.common_name := "Norway";
r.suffix := ".no";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NP";
r.common_name := "Nepal";
r.suffix := ".np";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NR";
r.common_name := "Nauru";
r.suffix := ".nr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NU";
r.common_name := "Niue";
r.suffix := ".nu";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "NZ";
r.common_name := "New Zealand";
r.suffix := ".nz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "OM";
r.common_name := "Oman";
r.suffix := ".om";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PA";
r.common_name := "Panama";
r.suffix := ".pa";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PE";
r.common_name := "Peru";
r.suffix := ".pe";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PF";
r.common_name := "French Polynesia";
r.suffix := ".pf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PG";
r.common_name := "Papua New Guinea";
r.suffix := ".pg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PH";
r.common_name := "Philippines";
r.suffix := ".ph";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PK";
r.common_name := "Pakistan";
r.suffix := ".pk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PL";
r.common_name := "Poland";
r.suffix := ".pl";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PM";
r.common_name := "Saint Pierre and Miquelon";
r.suffix := ".pm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PN";
r.common_name := "Pitcairn";
r.suffix := ".pn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PR";
r.common_name := "Puerto Rico";
r.suffix := ".pr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PS";
r.common_name := "Palestine, State of";
r.suffix := ".ps";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PT";
r.common_name := "Portugal";
r.suffix := ".pt";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PW";
r.common_name := "Palau";
r.suffix := ".pw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "PY";
r.common_name := "Paraguay";
r.suffix := ".py";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "QA";
r.common_name := "Qatar";
r.suffix := ".qa";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "RE";
r.common_name := "Réunion";
r.suffix := ".re";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "RO";
r.common_name := "Romania";
r.suffix := ".ro";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "RS";
r.common_name := "Serbia";
r.suffix := ".rs";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "RU";
r.common_name := "Russian Federation";
r.suffix := ".ru";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "RW";
r.common_name := "Rwanda";
r.suffix := ".rw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SA";
r.common_name := "Saudi Arabia";
r.suffix := ".sa";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SB";
r.common_name := "Solomon Islands";
r.suffix := ".sb";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SC";
r.common_name := "Seychelles";
r.suffix := ".sc";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SD";
r.common_name := "Sudan";
r.suffix := ".sd";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SE";
r.common_name := "Sweden";
r.suffix := ".se";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SG";
r.common_name := "Singapore";
r.suffix := ".sg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SH";
r.common_name := "Saint Helena, Ascension and Tristan da Cunha";
r.suffix := ".sh";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SI";
r.common_name := "Slovenia";
r.suffix := ".si";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SJ";
r.common_name := "Svalbard and Jan Mayen";
r.suffix := ".sj";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SK";
r.common_name := "Slovakia";
r.suffix := ".sk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SL";
r.common_name := "Sierra Leone";
r.suffix := ".sl";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SM";
r.common_name := "San Marino";
r.suffix := ".sm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SN";
r.common_name := "Senegal";
r.suffix := ".sn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SO";
r.common_name := "Somalia";
r.suffix := ".so";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SR";
r.common_name := "Sur.common_name";
r.suffix := ".sr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SS";
r.common_name := "South Sudan";
r.suffix := ".ss";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ST";
r.common_name := "Sao Tome and Principe";
r.suffix := ".st";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SV";
r.common_name := "El Salvador";
r.suffix := ".sv";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SX";
r.common_name := "Sint Maarten (Dutch part)";
r.suffix := ".sx";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SY";
r.common_name := "Syrian Arab Republic";
r.suffix := ".sy";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "SZ";
r.common_name := "Swaziland";
r.suffix := ".sz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TC";
r.common_name := "Turks and Caicos Islands";
r.suffix := ".tc";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TD";
r.common_name := "Chad";
r.suffix := ".td";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TF";
r.common_name := "French Southern Territories";
r.suffix := ".tf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TG";
r.common_name := "Togo";
r.suffix := ".tg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TH";
r.common_name := "Thailand";
r.suffix := ".th";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TJ";
r.common_name := "Tajikistan";
r.suffix := ".tj";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TK";
r.common_name := "Tokelau";
r.suffix := ".tk";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TL";
r.common_name := "Timor-Leste";
r.suffix := ".tl";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TM";
r.common_name := "Turkmenistan";
r.suffix := ".tm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TN";
r.common_name := "Tunisia";
r.suffix := ".tn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TO";
r.common_name := "Tonga";
r.suffix := ".to";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TR";
r.common_name := "Turkey";
r.suffix := ".tr";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TT";
r.common_name := "Trinidad and Tobago";
r.suffix := ".tt";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TV";
r.common_name := "Tuvalu";
r.suffix := ".tv";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TW";
r.common_name := "Taiwan, Province of China";
r.suffix := ".tw";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "TZ";
r.common_name := "Tanzania, United Republic of";
r.suffix := ".tz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "UA";
r.common_name := "Ukraine";
r.suffix := ".ua";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "UG";
r.common_name := "Uganda";
r.suffix := ".ug";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "UM";
r.common_name := "United States Minor Outlying Islands";
r.suffix := ".um";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "US";
r.common_name := "United States of America";
r.suffix := ".us";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "UY";
r.common_name := "Uruguay";
r.suffix := ".uy";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "UZ";
r.common_name := "Uzbekistan";
r.suffix := ".uz";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "VA";
r.common_name := "Holy See";
r.suffix := ".va";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "VC";
r.common_name := "Saint Vincent and the Grenadines";
r.suffix := ".vc";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "VE";
r.common_name := "Venezuela, Bolivarian Republic of";
r.suffix := ".ve";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "VG";
r.common_name := "Virgin Islands, British";
r.suffix := ".vg";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "VI";
r.common_name := "Virgin Islands, U.S.";
r.suffix := ".vi";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "VN";
r.common_name := "Viet Nam";
r.suffix := ".vn";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "VU";
r.common_name := "Vanuatu";
r.suffix := ".vu";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "WF";
r.common_name := "Wallis and Futuna";
r.suffix := ".wf";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "WS";
r.common_name := "Samoa";
r.suffix := ".ws";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "YE";
r.common_name := "Yemen";
r.suffix := ".ye";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "YT";
r.common_name := "Mayotte";
r.suffix := ".yt";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ZA";
r.common_name := "South Africa";
r.suffix := ".za";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ZM";
r.common_name := "Zambia";
r.suffix := ".zm";
btree_io.set( countries_file, r.iso3166, r );
r.iso3166 := "ZW";
r.common_name := "Zimbabwe";
r.suffix := ".zw";
btree_io.set( countries_file, r.iso3166, r );
btree_io.close( countries_file );

end init_countries;

-- vim: ft=spar

